[package]
name = "lazarus-life-admin"
version = "0.1.0"
description = "Lazarus Life Admin Panel"
authors = ["Lazarus Life Foundation"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.91"

[lib]
name = "admin_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.9.4", features = [] }
tauri-plugin-log = { version = "2.7.1", features = [] }

